language: ruby
rvm:
  - 2.3.0
before_install:
  - chmod +x ghp_deploy.sh
install:
  - bundle install
  - npm install
script: bundle exec jekyll build && grunt && ./ghp_deploy.sh
deploy:
  skip_cleanup: true